name: CI
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Standards-Check (Placeholder)
        run: echo "Lint/Tests/Solution Export hier integrieren"
